blog/config/routes.rb
Blog::Application.routes.draw do

  devise_for :users

  resources :articles do
    resources :comments
  end

  resources :users
  root :to => 'users#index'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :post, :title, :user_id
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {maximum: 50}
  validates :post, presence: true
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :body, :commenter
end

blog/app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :firstname, :lastname, :password, :first_name, :email, :password_confirmation

  has_many :articles

  validates :password, presence: true, length: { minimum: 8 }
end

blog/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include AbstractController::Callbacks
  protect_from_forgery

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :firstname, :lastname, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password) }
  end
end

blog/app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = repo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = repo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = repo.new_entity

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = repo.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = repo.new_entity(params[:article])

    respond_to do |format|
      if repo.save(@article)
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = repo.find(params[:id])

    respond_to do |format|
      if repo.update_attributes(@article, params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    repo.delete(params[:id])

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  def repo
    @repo ||= ArticlesRepository.new
  end
end

blog/app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    
    @article = articles_repo.find(params[:article_id])
    @comment = articles_repo.new_comment_entity(comment_params)
    @article.comments << @comment
    articles_repo.save(@article)
    redirect_to article_path(@article)
  end

  def destroy
    authenticate_user!
    @article = articles_repo.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @article.comments.delete @comment
    articles_repo.save(@article)
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commenter)
  end

  def articles_repo
    @articles_repo ||= ArticlesRepository.new
  end
end

blog/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = repo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = repo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = repo.new_entity

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = repo.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = repo.new_entity(params[:user])

    respond_to do |format|
      if repo.save(@user)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = repo.find(params[:id])

    respond_to do |format|
      if repo.update_attributes(@user, params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = repo.find(params[:id])
    repo.delete(@user)

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def repo
    @repo ||= UsersRepository.new
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_area :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<h2> Comments</h2>

<%= render @article.comments %>

<h2> Add new comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
<thead>
  <tr>
    <th>Title</th>
    <th>Post</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<% @articles.each do |article| %>
  <tr class = "<%= cycle("list_line_odd","list_line_even")%>"> 
    <td><%= article.title %></td>
    <td><%= article.post %></td>
    <td><%= article.user_id %></td>
    <td><%= link_to 'Show', article_path(article.id) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

blog/app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Post:</b>
  <%= @article.post %>
</p>

<p>
  <b>User:</b>
  <%= @article.user_id %>
</p>

<h2> Comments</h2>

<%= render @article.comments %>

<h2> Add new comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

blog/app/views/comments/_comment.html.erb
  <p>
    <strong> Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong> Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

blog/app/views/comments/_form.html.erb
<%= form_for([@article,@article.comments.build]) do |f| %>
  <div class="field"> 
    <%= f.label :commenter %> <br/>
    <%= f.text_field :"commenter", value: current_user ? current_user.firstname + ' ' + current_user.lastname : ''%> <br/>
  </div>

  <div class="field"> 
    <%= f.label :body%> <br/>
    <%= f.text_area :"body" %> <br/>
  </div>
  <div class="actions"> 
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<%= yield %>

</body>
</html>

blog/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

blog/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Firstname</th>
    <th>Lastname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= link_to 'Show', user_path(user.id) %></td>
    <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
    <td><%= link_to 'Destroy', user_path(user.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_registration_path %>
<%= link_to 'Articles', articles_path %>

blog/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Firstname:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>